# Generated by Django 3.2.9 on 2021-11-16 21:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapi',
            name='News_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='News_title', unique=True),
        ),
    ]
